# Generated by Django 5.2.8 on 2025-11-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('location', models.CharField(max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('accessibility', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='trips.user')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='SavedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_activities', to='trips.user')),
            ],
            options={
                'verbose_name_plural': 'Saved Activities',
                'db_table': 'saved_activities',
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
