# Generated by Django 4.2.27 on 2025-12-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_activity_latitude_activity_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this activity for the trip', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in itinerary')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='trips.activity')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='trips.trip')),
            ],
            options={
                'verbose_name_plural': 'Trip Activities',
                'db_table': 'trip_activities',
                'ordering': ['order', 'added_at'],
                'unique_together': {('trip', 'activity')},
            },
        ),
    ]
